// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbmtcbwfzwczztxzsytq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ibXRjYndmendjenp0eHpzeXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzcxNzksImV4cCI6MjA2NjAxMzE3OX0.Wpf8lp6TCFQ9aXpOnKXWlXOlWKuFQ8ARTY_Zak5JEiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);